(executable
 (name lexer)
 (modules lexer))

(executable
 (name ast)
 (modules ast))

(executable
 (name parser)
 (modules parser ast lexer))

(executable
 (name evaluator)
 (modules evaluator ast))

(executable
 (name compiler)
 (modules compiler ast lexer parser evaluator))

(test
 (name test_tiny_compiler)
 (modules test_tiny_compiler ast lexer parser evaluator)
 (libraries ounit2))
