cabal-version:       3.0
name:                haskell-toolbox
version:             0.1.0.0
synopsis:            Haskell learning toolbox
description:
  A minimal cabal project for testing your Haskell toolchain.
license:             NONE
author:              Learner
maintainer:          none@example.com
build-type:          Simple

executable haskell-toolbox
  main-is:           hello.hs
  hs-source-dirs:    src
  default-language:  Haskell2021
  ghc-options:       -Wall
